package skill

import (
	"bufio"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/smilemilks2021/easy-web/internal/browser"
)

// DomainToSkillName extracts a short skill name from a URL.
// "https://s-power.sheincorp.cn/xxx" → "s-power"
func DomainToSkillName(rawURL string) string {
	u, err := url.Parse(rawURL)
	if err != nil || u.Hostname() == "" {
		return "unknown"
	}
	host := u.Hostname()
	parts := strings.SplitN(host, ".", 2)
	return parts[0]
}

// SkillDir returns ~/.claude/skills/<name>
func SkillDir(name string) string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".claude", "skills", name)
}

// SkillPath returns ~/.claude/skills/<name>/SKILL.md
func SkillPath(name string) string {
	return filepath.Join(SkillDir(name), "SKILL.md")
}

// Generate creates or smart-merges a SKILL.md for the given captured requests.
// If skillName is empty it is derived from baseURL.
func Generate(reqs []*browser.CapturedRequest, baseURL, skillName string) error {
	if skillName == "" {
		skillName = DomainToSkillName(baseURL)
	}

	skillPath := SkillPath(skillName)

	if _, err := os.Stat(skillPath); err == nil {
		return smartMerge(skillPath, reqs, baseURL, skillName)
	}
	return writeNew(skillPath, reqs, baseURL, skillName)
}

// writeNew generates a fresh SKILL.md from scratch.
func writeNew(path string, reqs []*browser.CapturedRequest, baseURL, name string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}

	u, _ := url.Parse(baseURL)
	domain := u.Hostname()

	var sb strings.Builder

	// Frontmatter — matches easy-web SKILL.md format exactly
	sb.WriteString(fmt.Sprintf(`---
name: %s
description: |
  Use when automating %s (%s) — handles browser auth and exposes captured API
  endpoints as direct CLI calls without manual cookie management.
  Trigger: "帮我在 %s 上...", "查询 %s", "%s 操作", "在 %s 执行"
allowed-tools: Bash(easy-web:*)
---

# %s

## 认证

`+"```"+`bash
easy-web -u %s   # 登录一次，Cookie 自动缓存
`+"```"+`

## 接口列表
`, name, name, domain, name, name, name, name, name, baseURL))

	// Deduplicate requests
	seen := map[string]bool{}
	added := 0
	for _, req := range reqs {
		key := req.Method + " " + req.URL
		if seen[key] {
			continue
		}
		seen[key] = true
		sb.WriteString(buildAPIBlock(req))
		added++
	}

	sb.WriteString(fmt.Sprintf(
		"\n<!-- generated by easy-web skill gen at %s, %d APIs -->\n",
		time.Now().Format("2006-01-02 15:04:05"), added,
	))

	if err := os.WriteFile(path, []byte(sb.String()), 0644); err != nil {
		return err
	}
	fmt.Printf("[skill] created %s (%d APIs)\n", path, added)
	return nil
}

// smartMerge appends only new (not yet recorded) APIs to an existing SKILL.md.
// Existing content, comments, and hand-written notes are preserved.
func smartMerge(path string, reqs []*browser.CapturedRequest, baseURL, name string) error {
	existingContent, err := os.ReadFile(path)
	if err != nil {
		return err
	}

	existingURLs := extractRecordedURLs(string(existingContent))

	var newBlocks strings.Builder
	added := 0
	seen := map[string]bool{}

	for _, req := range reqs {
		key := req.Method + " " + req.URL
		if seen[key] || existingURLs[req.URL] {
			continue
		}
		seen[key] = true
		newBlocks.WriteString(buildAPIBlock(req))
		added++
	}

	if added == 0 {
		fmt.Printf("[skill] %s: no new APIs found, skill unchanged\n", name)
		return nil
	}

	merged := strings.TrimRight(string(existingContent), "\n") + "\n" +
		newBlocks.String() +
		fmt.Sprintf("\n<!-- updated by easy-web skill gen at %s, +%d APIs -->\n",
			time.Now().Format("2006-01-02 15:04:05"), added)

	if err := os.WriteFile(path, []byte(merged), 0644); err != nil {
		return err
	}
	fmt.Printf("[skill] %s: merged %d new APIs → %s\n", name, added, path)
	return nil
}

// buildAPIBlock renders a single API entry as a markdown section.
func buildAPIBlock(req *browser.CapturedRequest) string {
	u, _ := url.Parse(req.URL)
	path := u.Path
	if path == "" {
		path = "/"
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("\n### %s %s\n", req.Method, path))
	sb.WriteString("```bash\n")

	switch {
	case req.Body != "" && req.Method != "GET":
		sb.WriteString(fmt.Sprintf(
			"easy-web request -u %q \\\n  -X %s \\\n  -d %s\n",
			req.URL, req.Method, shellQuote(req.Body),
		))
	case req.Method != "GET":
		sb.WriteString(fmt.Sprintf(
			"easy-web request -u %q \\\n  -X %s\n",
			req.URL, req.Method,
		))
	default:
		sb.WriteString(fmt.Sprintf("easy-web request -u %q\n", req.URL))
	}

	sb.WriteString("```\n")
	return sb.String()
}

// shellQuote wraps s in single quotes for shell safety.
// If s contains single quotes, falls back to Go double-quote escaping.
func shellQuote(s string) string {
	if !strings.Contains(s, "'") {
		return "'" + s + "'"
	}
	return fmt.Sprintf("%q", s)
}

// extractRecordedURLs scans a SKILL.md and returns all URLs already present
// in `easy-web request -u "..."` lines.
func extractRecordedURLs(content string) map[string]bool {
	urls := map[string]bool{}
	scanner := bufio.NewScanner(strings.NewReader(content))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if !strings.HasPrefix(line, "easy-web request -u ") {
			continue
		}
		rest := strings.TrimPrefix(line, "easy-web request -u ")
		rest = strings.TrimSuffix(rest, ` \`)
		rest = strings.Trim(rest, `"'`)
		if rest != "" {
			urls[rest] = true
		}
	}
	return urls
}
